---
- hosts: all
  become: True
  tasks:
    - name: update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: install required applications
      yum:
        name: "{{ item }}"
        state: latest
      loop: '{{ packages_to_install }}'

    - name: start Docker engine service
      tags: start_docker_service
      service:
        name: docker
        state: started

    - name: create a welcome message
      template:
        src: /home/ansible/z-project/AnsibleRole/templates/welcome_msg.j2
        dest: /etc/profile.d/welcome_msg.sh
        owner: root
        group: root
        mode: '0644'

- hosts: tag_Name_web_server_dev
  become: True
  tasks:
    - name: run nginx container
      ansible.builtin.command:
        cmd: docker run -d -p 80:80 nginx

- hosts: tag_Name_web_server_prod
  become: True
  tasks:
    - name: run nginx container
      ansible.builtin.command:
        cmd: docker run -d -p 80:80 nginx         



